# Generated by Django 3.2 on 2022-11-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_ailment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ailment',
            name='other',
            field=models.TextField(blank=True, null=True),
        ),
    ]
