# Generated by Django 3.2 on 2022-10-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='area_of_specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
